name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 915467490133.dkr.ecr.us-east-1.amazonaws.com/todofrontend
          ECR_REPOSITORY: todofrontend
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY .

          # Log in to ECR
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      # - name: Deploy to App Runner
      #   uses: aws-actions/aws-app-runner-deploy@v1
      #   with:
      #     runner-name: <APP_RUNNER_NAME>
      #     region: us-east-1
      #     ecr-repository-name: todofrontend
      #     environment-variables: |
      #       # Add any required environment variables here
      #       VARIABLE_1=value1
      #       VARIABLE_2=value2
